[project]
name = "backend"
version = "0.1.0"
description = "Flask-based backend API for Neocord - a modern real-time communication platform. Features user authentication, instant messaging, community server management, and channel organization. Built with SQLAlchemy and Alembic for robust data management and migrations."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.0",
    "click>=8.1.7",
    "flask>=3.0.3",
    "flask-cors>=5.0.0",
    "flask-login>=0.6.3",
    "flask-migrate>=4.0.7",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "greenlet>=3.1.1",
    "gunicorn>=23.0.0",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.4",
    "mako>=1.3.6",
    "markupsafe>=3.0.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.0.1",
    "python-editor>=1.0.4",
    "six>=1.16.0",
    "sqlalchemy>=2.0.36",
    "werkzeug>=3.1.2",
    "wtforms>=3.2.1",
    "flask-socketio>=5.4.1",
]
