body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request. Please provide as much detail as possible to help us understand your suggestion.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: Describe the feature clearly and concisely, including any relevant context or reasons why this feature would be valuable.
      placeholder: "I would like to see..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like to see
      description: Describe the solution you have in mind, including any examples, workflows, or use cases that illustrate its usage.
      placeholder: "The ideal solution would be..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any related context, discussions, or links to issues that support this request.
      placeholder: "Related discussions or links..."