name: 🐞 Bug Report
description: Help us improve by reporting a bug.
title: "bug: "
labels: ["🐞❔ unconfirmed bug"]
body:
  - type: textarea
    attributes:
      label: Environment Information
      description: |
        Run this command in your project root and paste the results in a code block for context:
        ```bash
        bunx envinfo --system --binaries
        ```
      placeholder: "Output of `bunx envinfo`..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear description of the bug, including what you expected to happen.
      placeholder: "When I..."
    validations:
      required: true
  - type: input
    attributes:
      label: Link to Reproduction
      description: Provide a URL to a minimal reproducible example, if available.
      placeholder: "https://github.com/example/repo"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe how to trigger the bug with step-by-step instructions, including code snippets if applicable.
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Include any additional context, screenshots, or logs related to the bug.
      placeholder: "Additional context..."