services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - FLASK_APP=app
        - FLASK_ENV=production
        - DATABASE_URL=${DATABASE_URL}
        - SCHEMA=${SCHEMA}
        - SECRET_KEY=${SECRET_KEY}
    ports:
      - "443:443"
      - "80:80"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SCHEMA=${SCHEMA}
      - SECRET_KEY=${SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data: