name: Code Quality

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["dev", "main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  quality:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # JavaScript/TypeScript Quality Checks
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci --reporter=github .
        continue-on-error: true  # Allow the workflow to continue even if Biome fails

      # Python Quality Checks
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Ruff
        run: uv tool install ruff

      - name: Run Ruff Format Check
        run: ruff format --check backend/
        continue-on-error: true  # Allow the workflow to continue even if format check fails

      - name: Run Ruff Lint
        run: ruff check --output-format=github backend/
        continue-on-error: true  # Allow the workflow to continue even if lint fails

      # Report status
      - name: Report Status
        if: always()
        run: |
          if [ "${{ job.status }}" = "failure" ]; then
            echo "::error::Code quality checks failed. Please review the errors above."
            exit 1
          fi
